{"name": "Ошибка при неверном логине", "status": "passed", "start": 1751895226563, "stop": 1751895227058, "uuid": "e9e4b0bf-c850-441b-8b23-efe283a48f7c", "historyId": "5bf8f550dc17080d3f120eb4e949e80e", "testCaseId": "5bf8f550dc17080d3f120eb4e949e80e", "fullName": "tests.test_login_courier.TestLoginCourier#test_login_wrong_login", "labels": [{"name": "epic", "value": "Курьеры"}, {"name": "feature", "value": "Логин курьера"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-3L4TMJM"}, {"name": "thread", "value": "23940-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}